/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Transaksi;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Quinquee
 */
public class Form_transaksi_pengembalian extends javax.swing.JFrame {

    
    /**
     * Creates new form Form_transaksi_pengembalian
     */
    public Form_transaksi_pengembalian() {
        initComponents();
        empty_view();
        database_connection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        input_nobp = new javax.swing.JTextField();
        input_nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmb_kode = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        output_nama_buku = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        input_lama_keterlamabatan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        input_lama_pinjam = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        output_denda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        output_kembalian = new javax.swing.JTextField();
        input_bayar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Transaksi Pengembalian Buku ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("No BP");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        input_nobp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_nobp.setText("input_nobp");
        input_nobp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nobpActionPerformed(evt);
            }
        });
        jPanel1.add(input_nobp, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 150, -1));

        input_nama.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_nama.setText("input_nama");
        jPanel1.add(input_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 190, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nama Mahasiswa");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        cmb_kode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmb_kode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Input Kode Buku-", "B001", "B002", "B003" }));
        cmb_kode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kodeActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_kode, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kode Buku");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nama Buku");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        output_nama_buku.setBackground(new java.awt.Color(204, 204, 204));
        output_nama_buku.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        output_nama_buku.setText("output_nama_buku");
        output_nama_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                output_nama_bukuActionPerformed(evt);
            }
        });
        jPanel1.add(output_nama_buku, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 190, -1));

        jButton3.setBackground(new java.awt.Color(0, 102, 102));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Count");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 70, 40));

        jButton4.setBackground(new java.awt.Color(0, 102, 102));
        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 70, 40));

        jButton5.setBackground(new java.awt.Color(0, 102, 102));
        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Reset");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 70, 40));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 70, 40));

        input_lama_keterlamabatan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_lama_keterlamabatan.setText("input_lambat");
        input_lama_keterlamabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_lama_keterlamabatanActionPerformed(evt);
            }
        });
        jPanel1.add(input_lama_keterlamabatan, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 90, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Keterlambatan");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Lama Pinjam");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));

        input_lama_pinjam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_lama_pinjam.setText("input_pinjam");
        jPanel1.add(input_lama_pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 90, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Hari");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hari");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, -1, -1));

        output_denda.setBackground(new java.awt.Color(204, 204, 204));
        output_denda.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        output_denda.setText("output_denda");
        jPanel1.add(output_denda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 120, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Denda");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Jumlah Bayar  Rp.");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kembalian       Rp.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, -1, -1));

        output_kembalian.setBackground(new java.awt.Color(204, 204, 204));
        output_kembalian.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        output_kembalian.setText("output_kembalian");
        jPanel1.add(output_kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 120, -1));

        input_bayar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        input_bayar.setText("input_bayar");
        input_bayar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                input_bayarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                input_bayarMouseExited(evt);
            }
        });
        input_bayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                input_bayarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                input_bayarKeyReleased(evt);
            }
        });
        jPanel1.add(input_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 120, -1));

        jLabel1.setFont(new java.awt.Font("Wide Latin", 2, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Tranksaksi Pengembalian buku");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input_nobpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nobpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nobpActionPerformed

    private void cmb_kodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kodeActionPerformed
        String nama_buku=null;
        if(cmb_kode.getSelectedItem()=="-Input Kode Buku-"){
            empty_view();
        }
        else if(cmb_kode.getSelectedItem()=="B001"){
            nama_buku="Fisika";
        }
        else if(cmb_kode.getSelectedItem()=="B002"){
            nama_buku="Java & MySQL";
        }
        else if(cmb_kode.getSelectedItem()=="B003"){
            nama_buku="Bahasa Inggris";
        }

        output_nama_buku.setText(nama_buku);
    }//GEN-LAST:event_cmb_kodeActionPerformed

    private void output_nama_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_output_nama_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_output_nama_bukuActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int denda = 0;
        denda = Integer.parseInt(input_lama_keterlamabatan.getText())*1000;
        output_denda.setText(String.valueOf(denda));

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            //menyimpan data ke database ke dalam tabel pengembalian buku
            sql = "INSERT INTO pengembalian_buku VALUES ('"+input_nobp.getText()+
            "','"+input_nama.getText()+
            "','"+cmb_kode.getSelectedItem()+
            "','"+output_nama_buku.getText()+
            "','"+input_lama_pinjam.getText()+
            "','"+input_lama_keterlamabatan.getText()+
            "','"+output_denda.getText()+
            "','"+input_bayar.getText()+
            "','"+output_kembalian.getText()+
            "')";
            stat = con.createStatement();
            stat.execute(sql);
            JOptionPane.showMessageDialog(null, "Tersimpan.....");
            empty_view();
            stat.close();
        } 
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal....." + e);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        empty_view();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void input_lama_keterlamabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_lama_keterlamabatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_lama_keterlamabatanActionPerformed

    private void input_bayarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_bayarMouseClicked

    }//GEN-LAST:event_input_bayarMouseClicked

    private void input_bayarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_bayarMouseExited
        int kembalian;

        kembalian = Integer.parseInt(input_bayar.getText())-Integer.parseInt(output_denda.getText());

        output_kembalian.setText("" + kembalian);
    }//GEN-LAST:event_input_bayarMouseExited

    private void input_bayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_bayarKeyPressed

    }//GEN-LAST:event_input_bayarKeyPressed

    private void input_bayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_input_bayarKeyReleased

    }//GEN-LAST:event_input_bayarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_transaksi_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_transaksi_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_transaksi_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_transaksi_pengembalian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_transaksi_pengembalian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_kode;
    private javax.swing.JTextField input_bayar;
    private javax.swing.JTextField input_lama_keterlamabatan;
    private javax.swing.JTextField input_lama_pinjam;
    private javax.swing.JTextField input_nama;
    private javax.swing.JTextField input_nobp;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField output_denda;
    private javax.swing.JTextField output_kembalian;
    private javax.swing.JTextField output_nama_buku;
    // End of variables declaration//GEN-END:variables

    private void empty_view(){
    input_nobp.setText("");
    input_nama.setText("");
    cmb_kode.setSelectedIndex(0);
    output_nama_buku.setText("");
    input_lama_pinjam.setText("");
    input_lama_keterlamabatan.setText("");
    output_denda.setText("");
    input_bayar.setText("");
    output_kembalian.setText("");
    input_nobp.requestFocus();
} 

private Connection con;
private Statement stat;
private String sql;

private void database_connection(){
   try {
       Class.forName("com.mysql.jdbc.Driver");
       System.out.println("Driver Ditemukan...");
       try {
           //pemanggilan Database yang telah dibuat di mysql dengan nama perpustakaan
           String url = "jdbc:mysql://localhost:3306/perpustakaan?user=root&password=";
           con = DriverManager.getConnection(url);
           System.out.println("Terkoneksi.....");
           
       } catch (SQLException e){
           System.err.println("Tidak Terkoneksi.....");
       }
   } catch (ClassNotFoundException e){
       System.err.println("Driver Tidak Ditemukan.......");
   }
}

}
